### ISSUE TITLE
Create custom reference data for canine genome

### ISSUE THREAD

**Issue by rsg344** [Townsend-Lab-Yale/cancereffectsizeR#13]
I've been trying to create custom reference data using the build_RefCDS() function. I keep encountering the same error message: 

"Error in is(genome, "BSgenome") : 
  object 'BSgenome.Cfamiliaris.UCSC.canFam3' not found"

However, I downloaded the BSgenome package myself and looked at the available genomes within it and 'BSgenome.Cfamiliaris.UCSC.canFam3' is listed as one of them. I've also tried different variations of this name and nothing seems to work. I'm not sure how to proceed troubleshooting. Any guidance would be very helpful!

**Comment by jeff-mandell** [comment]
Hi, thanks for reaching out with your issue. Are you running like this?
`build_RefCDS(genome = BSgenome.Cfamiliaris.UCSC.canFam3, ... )`

The build_RefCDS function actually wants the assembly name, so the way to run is`build_RefCDS(genome = "canFam3", ...)`.

If you haven't already, you also need to install the canine genome package (not just BSgenome):
```
library(BiocManager)
install("BSgenome.Cfamiliaris.UCSC.canFam3")
```

**Comment by rsg344** [comment]
Yes, that worked once I installed the canine genome package and used the assembly name. Thank you so much!
