### ISSUE TITLE
Differential selection at gene level.

### ISSUE THREAD

**Issue by AISKhalil** [Townsend-Lab-Yale/cancereffectsizeR#17]
Thanks for developing the cancereffectsizeR tools!

We are performing some genomic analyses comparing the patients before and after treatments. Could we use cancereffectsizeR to quantify differential selection at the gene level ? E.g. genes that acquire more mutations (SNVs) after treatment, compared to treatment-naive samples. 

I have tried to use the "define_compound_variants" to split the mutations based on the clinical information (pretreated batch and treatment-naive batch) and quantify the differential selection between the two batches, but it doesn't work. Is there a way for doing that ?

**Comment by jeff-mandell** [comment]
Hi, thank you for using the package. You can use define_compound_variants() to calculate selection across arbitrary collections of variants, and you can then run ces_variant() on different groups of samples and compare selection. Do all the samples across both groups have the same sequencing coverage (as in, all generic WXS, or all WXS with the same specified exome capture kit)? If not, a key step is to ensure that all variants tested are covered across both groups.

Assuming that there are no such coverage issues, here is a template:

```
# choose any genes of interest
genes = c('PTEN', 'PIK3CA', 'EGFR', 'IDH1')

# Assuming "cesa" is the CESAnalysis object
variants = select_variants(cesa = cesa, genes = genes)
comp = define_compound_variants(cesa, variant_table = variants, by = 'gene', merge_distance = Inf)

# Assuming that patient-samples in the groups of interest are defined by grp1_samples and grp2_samples,
# and the all variants in comp are covered in all samples.
cesa = ces_variant(cesa, variants = comp, samples = grp1_samples, run_name = 'grp1')
cesa = ces_variant(cesa, variants = comp, samples = grp2_samples, run_name = 'grp2')
```

Typically, we test for significant differential selection using a likelihood ratio test:
```
# Run a combined inference on all samples in the previous runs
cesa = ces_variant(cesa = cesa, variants = comp, samples = c(grp1_samples, grp2_samples), run_name = 'combined')


# Merge output across runs (and trim some repetitive columns)
output = merge.data.table(cesa$selection$grp1, 
                          cesa$selection$grp2[, .(variant_name, included_with_variant, included_total, selection_intensity, 
                                                  loglikelihood, ci_low_95, ci_high_95)], by = 'variant_name', suffixes = c('.grp1', '.grp2'))
combined_run_output = cesa$selection$combined[, .(variant_name, selection_intensity, loglikelihood, ci_low_95, ci_high_95)]
names(combined_run_output) = paste0(names(combined_run_output), '.combined')
setnames(combined_run_output, 'variant_name.combined', 'variant_name')
output = merge.data.table(output, combined_run_output, by = 'variant_name')

# Calculate LRT p-values
output[, two_group_lik := loglikelihood.grp1 + loglikelihood.grp2]
output[, chisquared := -2 * (loglikelihood.combined - two_group_lik)]

# Under the null (effect in grp1 equals effect in grp2), the LRT statistic is chisquare-distributed.
output[, p := pchisq(chisquared, df = 1, lower.tail = F)]
```

**Comment by AISKhalil** [comment]
Thanks a lot Jeff for the prompt and detailed response!
